on: pull_request
jobs:
  eslint:
    runs-on: ubuntu-20.04
    name: eslint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v12
        with: 
          node-version: '12'
      - run: npm i
      - run: npx eslint 